on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build script.
    steps:
      - name: Begin build.
        id: build
        uses: pi-gen/docker-action@v1
        
