name: Build YggdrasilOS

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build script.
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies.
        run: export DEBIAN_FRONTEND=noninteractive; curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -; sudo apt-key fingerprint 0EBFCD88; sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"; sudo apt-get update; sudo apt-get install coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools bsdtar libcap2-bin grep rsync xz-utils file git curl bc docker-ce docker-ce-cli containerd.io apt-transport-https ca-certificates curl gnupg-agent software-properties-common

      - name: Begin build.
        run: ./build.sh
        
